[feat/#4] feat/#4/CreateRooms
beyond-sw-camp/be08-fin-EasyCheck-EasyStay-server pull request #23
Opened 2024-09-25 11:42 UTC by NAHYEON0713

## 📢 기능 설명
![localhost_8080_swagger-ui_index html (1)](https://github.com/user-attachments/assets/55886963-d981-4d50-b0f0-a93d48ddb2a5)

- 객실 등록 기능

<br>

## 연결된 issue
연결된 Issue를 자동을 닫기 위해 아래 {이슈넘버}를 입력해주세요. <br>
close #4 
<br>

## ✅ 체크리스트
- [ ] PR 제목 규칙 잘 지켰는가?
  - ex) [feat/#21] 회원 로그인 기능부분 구현
- [ ] 추가/수정사항을 설명하였는가?
- [ ] 이슈넘버를 적었는가?
- [ ] PR 베이스 브랜치를 확인하였는가?

2024-09-26 00:23 UTC, limjihoon99 approved these changes
Entity 만들 때 Accommodation 테이블 조인해야될듯!

2024-09-26 00:30 UTC, yongun2 commented on src/main/java/com/beyond/easycheck/EasycheckApplication.java
> +@EnableTransactionManagement
혹시 @EnableTransactionManagement 붙여준 이유가 있을까요?

2024-09-26 00:35 UTC, yongun2 requested changes
엔티티 연관관계

2024-09-26 00:35 UTC, yongun2 commented on src/main/java/com/beyond/easycheck/rooms/infrastructure/persistence/entity/RoomEntity.java
> +    private Long roomTypeId;
아이디 값이 아닌 RoomTypeEntity와 ManyToOne 연관관계를 맺어줘야 합니다.

2024-09-26 00:35 UTC, yongun2 commented on src/main/java/com/beyond/easycheck/rooms/infrastructure/persistence/entity/RoomRateEntity.java
> +    private Long seasonId;
여기도 마찬가지로 시즌 엔티티와 ManyToOne, 룸 엔티티와 ManyToOne 연관 관계를 설정해주시면 됩니다.

2024-09-26 02:45 UTC, jeongjinjoo approved these changes
잘했어욥

2024-09-27 07:49 UTC, NAHYEON0713 commented on src/main/java/com/beyond/easycheck/rooms/infrastructure/persistence/entity/RoomEntity.java
> +    private Long roomTypeId;
수정했습니당

2024-09-27 07:49 UTC, NAHYEON0713 commented on src/main/java/com/beyond/easycheck/rooms/infrastructure/persistence/entity/RoomRateEntity.java
> +    private Long seasonId;
수정했습니당

2024-09-27 07:50 UTC, NAHYEON0713 commented on src/main/java/com/beyond/easycheck/EasycheckApplication.java
> +@EnableTransactionManagement
BaseTimeEntity 사용하려고 @EnableJpaAuditing 어노테이션 붙이다가 함께 붙였는데 불필요해서 삭제 했습니당

2024-09-28 08:31 UTC, yongun2 approved these changes

2024-09-28 10:00 UTC, merged