feat: Suggestion Entity 생성 및 Create 기능 추가
beyond-sw-camp/be08-fin-EasyCheck-EasyStay-server pull request #27
Opened 2024-09-26 01:57 UTC by jeongjinjoo

## 📢 기능 설명
필요시 실행결과 스크린샷 첨부
![image](https://github.com/user-attachments/assets/181953cb-1b69-484c-a2c0-8af41966d76e)
![image](https://github.com/user-attachments/assets/a5bf660c-3921-4fa2-bfd6-1df0a710251c)

<br>

## 연결된 issue
연결된 Issue를 자동을 닫기 위해 아래 {이슈넘버}를 입력해주세요. <br>
close #{2}
<br>

## ✅ 체크리스트
- [ ] PR 제목 규칙 잘 지켰는가?
  - ex) [feat/#21] 회원 로그인 기능부분 구현
- [ ] 추가/수정사항을 설명하였는가?
- [ ] 이슈넘버를 적었는가?
- [ ] PR 베이스 브랜치를 확인하였는가?

2024-09-26 02:04 UTC, yongun2 requested changes
굿

2024-09-26 02:04 UTC, yongun2 commented on src/main/java/com/beyond/easycheck/infrastructure/persistence/entity/SuggestionEntity.java
> +    // suggestion_type : 유형
주석은 멤버변수 위쪽에 써주세여

2024-09-26 02:04 UTC, yongun2 commented on src/main/java/com/beyond/easycheck/infrastructure/persistence/entity/SuggestionEntity.java
> +    private String url;
erd에 명시된 컬럼명과 동일하게 해주세요

대신 카멜 케이스로
attechment_path -> attachmentPath

2024-09-26 02:04 UTC, yongun2 commented on src/main/java/com/beyond/easycheck/infrastructure/persistence/repository/SuggestionsRepository.java
> +@Repository
JpaRepository 상속받을 경우 요거 안붙여도 됩니다

2024-09-26 02:04 UTC, yongun2 commented on src/main/java/com/beyond/easycheck/ui/controller/SuggestionController.java
> +    public ResponseEntity<Void> createSuggestion(@RequestBody SuggestionCreateRequest suggestionCreateRequest) {
요거 @Notblank 이런거 적용 하려면 @Validated 어노테이션 붙여주세요
Ex) `@RequestBody @Validated SuggestionCreateRequest suggestionCreateRequest`

2024-09-26 02:04 UTC, yongun2 commented on src/main/java/com/beyond/easycheck/application/service/SuggestionService.java
> +        return Optional.of(suggestionsRepository.save(suggestion));
return 하실때 Optional로 감싸지 않아도 현재 로직에서는 괜찮을 것 같습니다.

Optional로 감싸게되면 해당 값이 null이 될 수도 있다는 의미인데

현재 저장이 성공적으로 되었다면 리턴되는 값이 null이 되지는 않을 것 같습니다.

2024-09-26 02:25 UTC, jeongjinjoo commented on src/main/java/com/beyond/easycheck/infrastructure/persistence/entity/SuggestionEntity.java
> +    // suggestion_type : 유형
옙

2024-09-26 02:27 UTC, yongun2 commented
pr 등록 할 때 
<img width="347" alt="스크린샷 2024-09-26 오전 11 26 14" src="https://github.com/user-attachments/assets/13640624-631f-4525-8f08-789022db9c07">

- Assignees
- Labels

요거 두개도 설정 해주세요

2024-09-26 02:28 UTC, jeongjinjoo commented on src/main/java/com/beyond/easycheck/infrastructure/persistence/entity/SuggestionEntity.java
> +    private String url;
알겠슴돠~

2024-09-26 02:29 UTC, jeongjinjoo commented on src/main/java/com/beyond/easycheck/infrastructure/persistence/repository/SuggestionsRepository.java
> +@Repository
굿

2024-09-26 02:29 UTC, jeongjinjoo commented on src/main/java/com/beyond/easycheck/ui/controller/SuggestionController.java
> +    public ResponseEntity<Void> createSuggestion(@RequestBody SuggestionCreateRequest suggestionCreateRequest) {
붙였슴돠

2024-09-26 02:35 UTC, yongun2 approved these changes
좋슴다

2024-09-27 00:03 UTC, limjihoon99 approved these changes

2024-09-27 08:25 UTC, merged