[feat/#62] feat/#62/CRUDRrooms
beyond-sw-camp/be08-fin-EasyCheck-EasyStay-server pull request #69
Opened 2024-09-28 15:28 UTC by NAHYEON0713

## 📢 기능 설명
- 객실 단일 조회
![image](https://github.com/user-attachments/assets/d6d17391-49ef-4236-a304-b381d2490f76)
<br>

- 객실 전체 조회 
![image](https://github.com/user-attachments/assets/941868ff-3c27-4fdb-9b11-572d9ed41d5d)
<br>

- 객실 수정
![image](https://github.com/user-attachments/assets/d367a0ab-958d-4ae9-be10-93dac40e3bcb)
<br>

- 객실 삭제
2번 객실 삭제 후 전체 조회 시 사라진 것 확인
![image](https://github.com/user-attachments/assets/2279f5f6-f60c-4567-acf3-67e2cb1f0fe8)

<br>

## 연결된 issue
연결된 Issue를 자동을 닫기 위해 아래 {이슈넘버}를 입력해주세요. <br>
close #62 
<br>

## ✅ 체크리스트
- [ ] PR 제목 규칙 잘 지켰는가?
  - ex) [feat/#21] 회원 로그인 기능부분 구현
- [ ] 추가/수정사항을 설명하였는가?
- [ ] 이슈넘버를 적었는가?
- [ ] PR 베이스 브랜치를 확인하였는가?

2024-09-29 06:33 UTC, yongun2 requested changes

2024-09-29 06:33 UTC, yongun2 commented on src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
> +    public RoomReadRequest readRoom(Long id) {
RoomReadRequest는 Client에서 데이터를 전달 받을 때만 사용하고 
Response로는 따로 View를 만들어서 반환하는게 좋을 것 같습니다.

2024-09-29 06:48 UTC, limjihoon99 approved these changes

2024-09-30 01:20 UTC, NAHYEON0713 commented on src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
> +    public RoomReadRequest readRoom(Long id) {
수정했습니다~~

2024-09-30 02:01 UTC, yongun2 approved these changes

2024-09-30 02:05 UTC, merged